# Generated by Django 2.2.4 on 2022-04-10 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220410_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации статьи'),
        ),
    ]
